/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamo36a06048-dev",
            "region": "us-east-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-2:35a4fa1f-298f-46ac-9e3d-0c2bcf8c3ff9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_cxAsWdr7D",
    "aws_user_pools_web_client_id": "49om2m8l236kq86dcca86h1jfn",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "api66db2874",
            "endpoint": "https://xk2e0c1vn5.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
